### ISSUE TITLE
Idea: compressed snapshots

### ISSUE THREAD

**Issue by basz** [prooph/snapshot-store#6]
snapshots should be able to store compressed data to save storage

e.g. via https://github.com/kjdev/php-ext-snappy

**Comment by prolic** [comment]
The snapshot store has no event hooks, so in order to do that, you need to
write your own snapshot store (copy/paste and add snappy).
I don't want to add snappy by default, because of the extra extension
requirement.

Am 01.04.2017 06:21 schrieb "Bas Kamer" <notifications@github.com>:

**Comment by codeliner** [comment]
or we add an ActionEventEmitterSnapshotStore ;)

**Comment by basz** [comment]
a simple in-out filter strategy (chain) would be flexible enough to provide something like this.

But I think I remember php is abe to serialise to different formats using ini configuration. I just can't seem to to find it now. Familiar with that?

**Comment by prolic** [comment]
So what we want are three things:
- serializing strategy
- compression strategy
- do not break BC

I think we have some options:
a) inject optional serializer and compressor (interfaces)
b) inject optional callbacks
c) the serializer could also take responsiblity for the compression, reducing the amount of dependencies

Callbacks:
What I like about the callback approach is we can inject a string that is the php function to call, that's very cool.

So I think B, what are your thoughts?

**Comment by basz** [comment]
I found what I was looking for but it relates to sessions:

> session.serialize_handler string
session.serialize_handler defines the name of the handler which is used to serialize/deserialize data. PHP serialize format (name php_serialize), PHP internal formats (name php and php_binary) and WDDX are supported (name wddx). WDDX is only available, if PHP is compiled with WDDX support. php_serialize is available from PHP 5.5.4. php_serialize uses plain serialize/unserialize function internally and does not have limitations that php and php_binary have. Older serialize handlers cannot store numeric index nor string index contains special characters (| and !) in $_SESSION. Use php_serialize to avoid numeric index or special character errors at script shutdown. Defaults to php.

thoughts;
- serializer and compressor -> interfaces seem a bit more expressive then callbacks, but they are faster right? B. is fine, A is fine too.

- serialiser strategy -> i think the build-in php serialiser is the option that is able to work with reconstructing object references. I consider that as requirement. Therefore a strategy for serialisation doesn't add much value?

- compressor strategy -> how about http://php.net/manual/en/stream.filters.php? filter can be stacked, eg. serialise > encrypt > compress > storage > decompress > decrypt > deserialise.

**Comment by prolic** [comment]
Igbinary is an option for serializing objects as well.

Am 04.04.2017 21:22 schrieb "Bas Kamer" <notifications@github.com>:

I found what I was looking for but it relates to sessions:

session.serialize_handler string
session.serialize_handler defines the name of the handler which is used to
serialize/deserialize data. PHP serialize format (name php_serialize), PHP
internal formats (name php and php_binary) and WDDX are supported (name
wddx). WDDX is only available, if PHP is compiled with WDDX support.
php_serialize is available from PHP 5.5.4. php_serialize uses plain
serialize/unserialize function internally and does not have limitations
that php and php_binary have. Older serialize handlers cannot store numeric
index nor string index contains special characters (| and !) in $_SESSION.
Use php_serialize to avoid numeric index or special character errors at
script shutdown. Defaults to php.

thoughts;

   -

   serializer and compressor -> interfaces seem a bit more expressive then
   callbacks, but they are faster right? B. is fine, A is fine too.
   -

   serialiser strategy -> i think the build-in php serialiser is the option
   that is able to work with reconstructing object references. I consider that
   as requirement. Therefore a strategy for serialisation doesn't add much
   value?
   -

   compressor strategy -> how about http://php.net/manual/en/
   stream.filters.php? filter can be stacked, eg. serialise > encrypt >
   compress > storage > decompress > decrypt > deserialise.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/prooph/snapshot-store/issues/6#issuecomment-291497660>,
or mute the thread

**Comment by basz** [comment]
aha!

callback strategy would be simplest. I would also argue that the need for compression/processing becomes much less important. (igbinary reduces by ~50% they claim)

Callback could be 'serialize' or 'igbinary_serialize' as you suggested. If one would want to do multiple  processing steps. No need to differentiate between 'serialisation strategies' and 'compression strategies'.

**Comment by basz** [comment]
something like [this](https://github.com/prooph/pdo-snapshot-store/pull/11) could work, no BC
